version: "3.9"

services:
  backend:
    container_name: spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    container_name: nginx-frontend
    build:
      context: ./proyecto_front/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
